version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php_app
    restart: always
    volumes:
      - ./app:/var/www/html

  web:
    image: nginx:alpine
    container_name: nginx_web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app