server {
    listen 80;
    server_name localhost;

    root /var/www/html;
    index index.php;

    # Configuração para tratar rotas e ficheiros
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Encaminhar ficheiros .php para o container do PHP-FPM via FastCGI
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}